python 2_train_stare_dynamic.py --model UNetMI --fold 1 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 2 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 3 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 4 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 5 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 6 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 7 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 8 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 9 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 10 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 11 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 12 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 13 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 14 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 15 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 16 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 17 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 18 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 19 --lr_decay --data_augmentation --batch_size 512 --device 0
python 2_train_stare_dynamic.py --model UNetMI --fold 20 --lr_decay --data_augmentation --batch_size 512 --device 0
